name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build:
    strategy:
      matrix:
        configure-preset: [clang-cl]
        build-preset: [debug, release]
        os: [windows-2022]
        
    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run Vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: '1370b2c88f1e683c5c6a2465133eaa9a9b3ee679'
        vcpkgJsonGlob: 'vcpkg.json'
    
    - name: Run CMake
      uses: lukka/run-cmake@v10
      with:
        configurePreset: '${{matrix.configure-preset}}'
        buildPreset: '${{matrix.configure-preset}}-${{matrix.build-preset}}'
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.build-type}} Binaries
        path: |
          ${{github.workspace}}/builds/${{matrix.configure-preset}}/ar/${{matrix.build-type}}/
          ${{github.workspace}}/builds/${{matrix.configure-preset}}/lib/${{matrix.build-type}}/
          ${{github.workspace}}/builds/${{matrix.configure-preset}}/bin/${{matrix.build-type}}/
